# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

# Examples of API resource mapping, learn more at
# https://github.com/dunglas/DunglasApiBundle
    resource.user:
        parent:    "api.resource"
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.user.order_filter" ] ]
        arguments: [ "AppBundle\\Entity\\User" ]
        tags:      [ { name: "api.resource" } ]

    resource.user.order_filter:
        parent:    "api.doctrine.orm.order_filter"
        arguments: [ { "list_order": ASC } ]